<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NMaier.SimpleDlna.FileMediaServer</RootNamespace>
    <AssemblyName>SimpleDlna.FileMediaServer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" />
    <PackageReference Include="TagLibSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\server\server.csproj" />
    <ProjectReference Include="..\thumbs\thumbs.csproj" />
    <ProjectReference Include="..\util\util.csproj" />
  </ItemGroup>

</Project>
