<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NMaier.SimpleDlna.Utilities</RootNamespace>
    <AssemblyName>SimpleDlna.Utilities</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
  </ItemGroup>

</Project>
