<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NMaier.SimpleDlna.Thumbnails</RootNamespace>
    <AssemblyName>SimpleDlna.Thumbnails</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\server\server.csproj" />
    <ProjectReference Include="..\util\util.csproj" />
  </ItemGroup>

</Project>
